# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "fbf60f6302b3e92e01e42fa7dc123f70"
name = "abdullah-app"
handle = "abdullah-app-1"
application_url = "https://7c28-122-129-85-58.ngrok-free.app"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "abdullah-brainx.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://7c28-122-129-85-58.ngrok-free.app/auth/callback",
  "https://7c28-122-129-85-58.ngrok-free.app/auth/shopify/callback",
  "https://7c28-122-129-85-58.ngrok-free.app/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks"

[pos]
embedded = false
